[tool.poetry]
name = "opentakserver"
version = "0.1.0"
description = ""
authors = ["OpenTAKServer <opentakserver@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.0"
colorlog = "^6.7.0"
flask-socketio = "^5.3.6"
bs4 = "^0.0.1"
datetime = "^5.3"
pika = "^1.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
