[tool.poetry]
name = "opentakserver"
version = "0.1.0"
description = ""
authors = ["OpenTAKServer <opentakserver@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
adsbxcot = "6.0.4"
beautifulsoup4 = "4.12.3"
colorlog = "6.8.2"
datetime = "5.3"
ffmpeg-python = "0.2.0"
flask = "3.0.2"
flask-apscheduler = "1.13.1"
flask-cors = "4.0.0"
Flask-Security-Too = {version="5.4.2", extras=["common", "mfa"]}
flask-socketio = "5.3.6"
flask-sqlalchemy = "3.1.1"
eventlet = "0.35.2"
gevent = "23.9.1"
lxml = "5.1.0"
pika = "1.3.2"
psutil = "5.9.8"
pygc = "1.3.0"
PyJWT = "2.8.0"
pytak = "6.3.2"
pytest = "7.4.4"
pytest-cov = "4.1.0"
python = "^3.10"
python-socketio = {extras = ["client", "websocket_client", "asyncio_client"], version = "5.10.0"}
pyOpenSSL = "23.3.0"
pyotp = "2.9.0"
PyYAML = "6.0.1"
sqlalchemy = "2.0.28"
sqlalchemy-utils = "0.41.1"
tldextract = "5.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
