[tool.poetry]
name = "opentakserver"
version = "0.1.0"
description = ""
authors = ["OpenTAKServer <opentakserver@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.0"
adsbxcot = "^6.0.4"
bleach = "*"
colorlog = "^6.7.0"
ffmpeg-python = "^0.2.0"
flask-apscheduler = "^1.13.1"
flask-mail = "^0.9.1"
flask-socketio = "^5.3.6"
bs4 = "^0.0.1"
datetime = "^5.3"
eventlet = "^0.35.0"
gevent = "^23.9.1"
lxml = "^5.0.0"
pika = "^1.3.2"
psutil = "^5.9.7"
pytak = "^6.2.4"
pytest = "^7.4.4"
pytest-cov = "^4.1.0"
sqlalchemy = "^2.0.23"
sqlalchemy-utils = "^0.41.1"
flask-sqlalchemy = "^3.1.1"
Flask-Security-Too = "^5.3.2"
flask-cors = "^4.0.0"
pyOpenSSL = "^23.3.0"
cryptography = "^41.0.7"
python-socketio = {extras = ["client", "websocket_client", "asyncio_client"], version = "5.10.0"}
pygc = "^1.3.0"
PyJWT = "^2.8.0"
qrcode = "^7.4.2"
pyotp = "^2.9.0"
PyYAML = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
