apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opentakserver.fullname" . }}-backend-data
  labels:
    {{- include "opentakserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size | default "1Gi" }}
