{{- if .Values.mediamtx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentakserver.fullname" . }}-mediamtx-config
  labels:
    {{- include "opentakserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: mediamtx
data:
  mediamtx.yml: |
    paths:
      "~^.*_h264$":
      all_others:
        runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$MTX_PATH?token=taks-secret-token -c:v libx264 -preset ultrafast -tune zerolatency -b:v 600k -c:a copy -f rtsp rtsp://localhost:$RTSP_PORT/${MTX_PATH}_h264?token=taks-secret-token
{{- end }}
