{{- if .Values.mediamtx.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opentakserver.fullname" . }}-mediamtx
  labels:
    {{- include "opentakserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: mediamtx
spec:
  replicas: {{ .Values.mediamtx.replicaCount }}
  selector:
    matchLabels:
      {{- include "opentakserver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mediamtx
  template:
    metadata:
      labels:
        {{- include "opentakserver.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mediamtx
    spec:
      containers:
        - name: mediamtx
          image: "{{ .Values.mediamtx.image.repository }}:{{ .Values.mediamtx.image.tag }}"
          imagePullPolicy: {{ .Values.mediamtx.image.pullPolicy }}
          ports:
          resources:
            {{- toYaml .Values.mediamtx.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "opentakserver.fullname" . }}-mediamtx-config

{{- end -}}
