{{- if .Values.mediamtx.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opentakserver.fullname" . }}-mediamtx-routing
  labels:
    {{- include "opentakserver.labels" . | nindent 4 }}
  annotations:
    # Use the same middleware to strip prefixes
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "opentakserver.fullname" . }}-strip-webrtc@kubernetescrd
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /webrtc
            pathType: Prefix
            backend:
              service:
                name: {{ include "opentakserver.fullname" $ }}-mediamtx
                port:
                  number: 8889
          - path: /hls
            pathType: Prefix
            backend:
              service:
                name: {{ include "opentakserver.fullname" $ }}-mediamtx
                port:
                  number: 8888
    {{- end }}
{{- end }}
