apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opentakserver.fullname" . }}-recordings
  labels:
    {{- include "opentakserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.recordings.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.recordings.persistence.size | default "10Gi" }}
  {{- if .Values.recordings.persistence.storageClass }}
  storageClassName: {{ .Values.recordings.persistence.storageClass }}
  {{- end }}
